services:
  messagebroker:
    image: rabbitmq:management-alpine

  contacts.db:
    image: mcr.microsoft.com/mssql/server:2022-latest

  create-contact.api:
    image: ${DOCKER_REGISTRY-}create-contact.api
    build:
      context: .
      dockerfile: src/CreateContact.API/Dockerfile
    networks:
      - contactmanager-network

  contactmanager.prometheus:
    image: prom/prometheus:latest

  contactmanager.grafana:
    image: grafana/grafana:latest
