apiVersion: v1
kind: Service
metadata:
  name: create-contact-svc
  labels:
    app: contact-api
spec:
  selector:
    app: contact-api
    service: create
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080