name: CI Pipeline - Contact Microservice API

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./CreateContact.sln
      
    - name: Build
      run: dotnet build ./CreateContact.sln --no-restore
      
    - name: Test
      run: dotnet test ./CreateContact.sln --no-build --verbosity normal
